### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bhack** [chiaki530/leapvo#1]
Is there a license for the repo?

**Comment by wrchen530** [comment]
Hi, thanks for the notice! We follow the licences of [CoTracker](https://github.com/facebookresearch/co-tracker?tab=License-1-ov-file) and [DPVO](https://github.com/princeton-vl/DPVO/tree/main?tab=MIT-1-ov-file).

**Comment by bhack** [comment]
But these two licenses are different

**Comment by wrchen530** [comment]
In this case, we need to follow the [CoTracker](https://github.com/facebookresearch/co-tracker?tab=License-1-ov-file) which is stricter.
