### ISSUE TITLE
Estimated Vs calibrated intrinsics

### ISSUE THREAD

**Issue by bhack** [chiaki530/leapvo#2]
Have you tried to bootstrap the system with estimated initial intrisics instead of calibrated camera and then refine it in your custom BA stage?

**Comment by wrchen530** [comment]
Hi @bhack, we haven't yet optimized the camera intrinsics in the current implementation. It is indeed possible by modifying the optimization objective to include refining the camera parameters. We plan to leave it for further extension.

**Comment by Davidyao99** [comment]
Does this mean that currently, LEAP-VO uses GT intrinsics for prediction?

**Comment by fangli333** [comment]
> Does this mean that currently, LEAP-VO uses GT intrinsics for prediction?

the same question from me

**Comment by wrchen530** [comment]
Yes, LEAP-VO currently only supports given intrinsics (either ground truth or estimated by other methods).
