### ISSUE TITLE
Great work! Will you release the training script? Thx

### ISSUE THREAD

**Issue by Xiaoyuan-Isaac-Wang** [chiaki530/leapvo#3]

**Comment by wrchen530** [comment]
Hi @luminousking, we are planning to release the training script soon. Additionally, we are considering an updated version of LEAP-VO and hope to release both together. Stay tuned :)

**Comment by C-H-Chien** [comment]
> Hi [@luminousking](https://github.com/luminousking), we are planning to release the training script soon. Additionally, we are considering an updated version of LEAP-VO and hope to release both together. Stay tuned :)

Hi, I am following up if there is an update. It's been a while and it would be highly appreciated if the training script is released. Thanks!
