### ISSUE TITLE
How did you avoid keypoint duplication?

### ISSUE THREAD

**Issue by nnop** [chiaki530/leapvo#7]
Hi, weirong,

Great work! I have a question about the allocation of new keypoints in new frame. In the paper, you mentioned:
> When a new image frame It is captured at time t, we sample N new keypoints from this image to initiate point tracking.

What if you sampled at  the position a tracked trajectory is continuing? Had you do some work to distinguish these points with tracked points?

**Comment by wrchen530** [comment]
Hi @nnop , in the current implementation, we didn't distinguish the new keypoints from the old tracked points, treating them as independent point trajectories. Each keyframe is associated with its source frame and is tracked using the LEAP front-end within the window.
