### ISSUE TITLE
DPVO Benchmark

### ISSUE THREAD

**Issue by Davidyao99** [chiaki530/leapvo#8]
I noticed that you included DPVO in many of your benchmarks. I was wondering what config did you use to run DPVO as I am not able to reproduce the DPVO numbers in your table. Hoping to run DPVO for my own benchmarks on similar datasets.

One observation for DPVO is that I believe it does not have a dynamic object removal component, but it still seems to perform relatively well for Sintel.

**Comment by wrchen530** [comment]
Hi @Davidyao99, we use the default.yaml to run DPVO. For the Sintel evaluation, we modified the I/O function to allow loading the ground truth camera intrinsics for every frame, as some sequences have varying camera parameters. 

Although DPVO doesn't include dynamic object removal, I believe it still effectively models how each point contributes to camera motion.
